interface IEntryRatings {
  diversity: number,
  fairness: number,
  humanity: number,
  renewable: number,
  solidarity: number,
  total: number,
  transparency: number,
}

export default interface IEntry {
  categories: string[],
  city?: string,
  country?: string | null,
  created?: number,
  description: string,
  email?: string,
  homepage?: string,
  id: string,
  image_link_url?: string | null,
  image_url?: string,
  lat: number,
  license?: string,
  lng: number,
  ratings?: IEntryRatings | string[],
  street?: string,
  tags: string[],
  telephone?: string,
  title: string,
  version?: number,
  zip?: string,
}
