// Generated by CoffeeScript 1.12.4
(function() {
  (require("chai")).should();

  describe("Normalization", function() {
    var N;
    N = require("../../src/util/normalize");
    return describe("url", function() {
      return it("should add missing protocol", function() {
        N.url("foo.bar").should.equal("http://foo.bar");
        N.url("http://foo.bar").should.equal("http://foo.bar");
        N.url("https://foo.bar").should.equal("https://foo.bar");
        N.url("").should.equal("");
        return should.not.exist(N.url());
      });
    });
  });

}).call(this);
