# Copyright (c) 2015 Markus Kohlhase <mail@markus-kohlhase.de>

module.exports =

  TOGGLE_SEARCH_CATEGORY  : 'TOGGLE_SEARCH_CATEGORY'
  TOGGLE_MENU             : 'TOGGLE_MENU'

  SHOW_NEW_ENTRY          : 'SHOW_NEW_ENTRY'
  SHOW_INFO               : 'SHOW_INFO'

  CLOSE_NEW_ENTRY         : 'CLOSE_NEW_ENTRY'

  SET_MARKER              : 'SET_MARKER'
  SET_MAP_CENTER          : 'SET_MAP_CENTER'
  SET_ZOOM                : 'SET_ZOOM'
  SET_CURRENT_ENTRY       : 'SET_CURRENT_ENTRY'
  SET_SEARCH_TEXT         : 'SET_SEARCH_TEXT'

  HIGHLIGHT_ENTRIES       : 'HIGHLIGHT_ENTRIES'

  SEARCH_RESULT           : 'SEARCH_RESULT'
  ENTRIES_RESULT          : 'ENTRIES_RESULT'
  CATEGORIES_RESULT       : 'CATEGORIES_RESULT'
  NEW_ENTRY_RESULT        : 'NEW_ENTRY_RESULT'
