import LICENSES from "./Licenses"

module.exports = {
  NEW_ENTRY_LICENSE: LICENSES.CC0,
  TILEHOSTING_API_KEY: "HOG1gcOUF2mFfwTfD5zS",
  MOVEEND_DELAY: 750,
  ZOOMEND_DELAY: 750,
  SEARCH_DELAY: 500
}