# Copyright (c) 2015 Markus Kohlhase <mail@markus-kohlhase.de>

module.exports =
  EDIT              : 'EDIT'
  NEW               : 'NEW'
  RESULT            : 'RESULT'
  ENTRY             : 'ENTRY'
  INFO              : 'INFO'
  MAP_INFO          : 'MAP_INO'
  DONATE            : 'DONATE'
  JOIN              : 'JOIN'
  TEAM              : 'TEAM'
  SUPPORTERS        : 'SUPPORTERS'
  IMPRINT           : 'IMPRINT'
  OPEN_SOURCE       : 'OPEN_SOURCE'
  WAIT              : 'WAIT'
  IO_ERROR          : 'IO_ERROR'
  LOCATE            : 'LOCATE'
  LOCATE_DISABLED   : 'LOCATE_DISABLED'
  DONATE_FOR_EVENTS : 'DONATE_FOR_EVENTS'
