export const EDIT = 'EDIT'
export const NEW = 'NEW'
export const NEW_RATING = 'NEW_RATING'
export const NEW_COMMENT = 'NEW_COMMENT'
export const RESULT = 'RESULT'
export const ENTRY = 'ENTRY'
export const INFO = 'INFO'
export const CONTACT = 'CONTACT'
export const MAP_INFO = 'MAP_INO'
export const DONATE = 'DONATE'
export const JOIN = 'JOIN'
export const TEAM = 'TEAM'
export const SUPPORTERS = 'SUPPORTERS'
export const IMPRINT = 'IMPRINT'
export const PRIVACY_STATEMENT = 'PRIVACY_STATEMENT'
export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const EMAIL_CONFIRMED = 'EMAIL_CONFIRMED'
export const CONFIRM_EMAIL_ERROR ='CONFIRM_EMAIL_ERROR'
export const CONFIRMING_EMAIL ='CONFIRMING_EMAIL'
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'
export const OPEN_SOURCE = 'OPEN_SOURCE'
export const WAIT = 'WAIT'
export const IO_ERROR = 'IO_ERROR'
export const LOCATE = 'LOCATE'
export const LOCATE_DISABLED = 'LOCATE_DISABLED'
export const DONATE_FOR_EVENTS = 'DONATE_FOR_EVENTS'
export const SUBSCRIBE_TO_BBOX = 'SUBSCRIBE_TO_BBOX'
export const EMBED = 'EMBED'

export default {
  EDIT,
  NEW,
  NEW_RATING,
  NEW_COMMENT,
  RESULT,
  ENTRY,
  INFO,
  CONTACT,
  MAP_INFO,
  DONATE,
  JOIN,
  TEAM,
  SUPPORTERS,
  IMPRINT,
  PRIVACY_STATEMENT,
  REGISTER,
  REGISTER_SUCCESS,
  EMAIL_CONFIRMED,
  CONFIRM_EMAIL_ERROR,
  CONFIRMING_EMAIL,
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGOUT,
  OPEN_SOURCE,
  WAIT,
  IO_ERROR,
  LOCATE,
  LOCATE_DISABLED,
  DONATE_FOR_EVENTS,
  SUBSCRIBE_TO_BBOX,
  EMBED
}
