// TODO: module.exports = {
// TODO:   NO_ROUTING: "NO_ROUTING",
// TODO:   SHOW_ENTRY: "SHOW_ENTRY",
// TODO:   CHANGE_CENTER: "CHANGE_CENTER",
// TODO:   CHANGE_ZOOM: "CHANGE_ZOOM",
// TODO:   CHANGE_SEARCH: "CHANGE_SEARCH",
// TODO:   CONFIRM_EMAIL: "CONFIRM_EMAIL",
// TODO:   CHANGE_SIDEBAR_VISIBILITY: "CHANGE_SIDEBAR_VISIBILITY",
// TODO:   CHANGE_SEARCH_CATEGORIES: "CHANGE_SEARCH_CATEGORIES"
// TODO: };
