module.exports = {
  NO_ROUTING: 'NO_ROUTING',
  SHOW_ENTRY: 'SHOW_ENTRY',
  CHANGE_CENTER: 'CHANGE_CENTER',
  CHANGE_ZOOM: 'CHANGE_ZOOM',
  CHANGE_SEARCH: 'CHANGE_SEARCH',
  CONFIRM_EMAIL: 'CONFIRM_EMAIL',
  CHANGE_SIDEBAR_VISIBILITY: 'CHANGE_SIDEBAR_VISIBILITY'
}