// Generated by CoffeeScript 1.12.4
(function() {
  (require("chai")).should();

  describe("map reducer", function() {
    var Actions, R;
    R = require("../../src/reducers/map");
    Actions = require("../../src/Actions");
    it("should be a function", function() {
      return R.should.be.a("function");
    });
    describe("marker", function() {
      return it("should be set when the action was fired", function() {
        var action, actionToBeDispatched, marker;
        actionToBeDispatched = Actions.setMarker({
          lat: 5,
          lng: 7
        });
        action = null;
        actionToBeDispatched((function(arg) {
          return action = arg;
        }), (function() {
          return {};
        }));
        marker = R({}, action).marker;
        marker.lat.should.equal(5);
        return marker.lng.should.equal(7);
      });
    });
    return describe("bounding box", function() {
      return it("should be set when the action was fired", function() {
        var action, bbox;
        action = Actions.setBbox({
          foo: "bar"
        });
        bbox = R({}, action).bbox;
        return bbox.foo.should.equal("bar");
      });
    });
  });

}).call(this);
